---
- name: Install FreeIPA Server on CentOS
  hosts: ipa_server
  become: yes
  tasks:
    - name: Ensure that EPEL and FreeIPA repositories are enabled
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - ftp://ftp.icm.edu.pl/vol/rzm7/linux-centos-vault/7.9.2009/updates/x86_64/Packages/ipa-server-4.6.8-5.el7.centos.16.x86_64.rpm

    - name: Install necessary packages for FreeIPA server
      yum:
        name:
          - ipa-server
          - bind
          - bind-dyndb-ldap
          - ipa-server-dns
        state: present

    - name: Install and configure FreeIPA server (unattended)
      command: >
        ipa-server-install --unattended
        --domain=mc.local
        --realm=MC.LOCAL
        --ds-password=12345678
        --admin-password=12345678
        --setup-dns
        --no-forwarders

    - name: Start and enable IPA services
      systemd:
        name: ipa
        enabled: yes
        state: started
